# Generated by Django 4.2.5 on 2023-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_genre_films_field_films_films_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='films_field',
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ManyToManyField(to='films.genre'),
        ),
    ]
