# Generated by Django 4.2.5 on 2023-12-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_films_films_field_films_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.films')),
            ],
        ),
    ]
